# This Docker Compose file defines a multi-container application with the following configuration:
#
# Version:
# - Uses Docker Compose file format version 3.3.
#
# Services:
# - node-app:
#   - A service for running a Node.js application.
#   - Build:
#     - The build context is set to the current directory (".").
#     - The Dockerfile used for building the image is named "Dockerfile".
#   - Ports:
#     - Maps port 3000 on the host to port 3000 in the container.
#     - Maps port 3001 on the host to port 3001 in the container.
#   - Volumes:
#     - Mounts the current directory (".") to the "/app" directory inside the container.
#   - Environment:
#     - Sets the environment variable NODE_ENV to "production".
#   - Restart Policy:
#     - Configured to restart the container unless it is explicitly stopped.
#   - Networks:
#     - Connects to a custom network named "vite_network".
#
# Networks:
# - vite_network:
#   - A custom bridge network used for inter-service communication.
version: '3.3'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - vite_network

networks:
  vite_network:
    driver: bridge
